<?php

include_once('theme/views_facetedsearch.theme.inc');

/**
 * Implements hook_views_plugins().
 */
function views_facetedsearch_views_plugins() {
  return array(
    'style' => array(
      'facetedsearch' => array(
        'title' => t('Faceted Search'),
        'help' => t('Display the results as a Faceted Search.'),
        'handler' => 'views_facetedsearch_plugin_style_facetedsearch',
        'uses options' => TRUE,
        'uses row plugin' => TRUE,
        'uses grouping' => FALSE,
        'uses row class' => TRUE,
        'type' => 'normal',
        'path' => drupal_get_path('module', 'views_facetedsearch'),
        'theme' => 'views_facetedsearch',
        'theme path' => drupal_get_path('module', 'views_facetedsearch') . '/theme',
        'theme file' => 'views_facetedsearch.theme.inc',
      ),
    ),
  );
}
